<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mbpdepich" name="fr.eseo.atribus.dao.ExerciceDaoImplTest" tests="5" failures="0" timestamp="20 May 2016 10:12:40 GMT" time="0.696" errors="1">
  <testcase name="trouverParQuestionReponse" time="0.549" classname="fr.eseo.atribus.dao.ExerciceDaoImplTest"/>
  <testcase name="ajouterBonExercice" time="0.078" classname="fr.eseo.atribus.dao.ExerciceDaoImplTest"/>
  <testcase name="supprimerExercice" time="0.026" classname="fr.eseo.atribus.dao.ExerciceDaoImplTest">
    <error type="fr.eseo.atribus.dao.DaoException" message="com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column &#039;id_matiere&#039; in &#039;field list&#039;">
      <![CDATA[fr.eseo.atribus.dao.DaoException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'id_matiere' in 'field list'
	at fr.eseo.atribus.dao.ExerciceDaoImpl.supprimerAvecRollback(ExerciceDaoImpl.java:219)
	at fr.eseo.atribus.dao.ExerciceDaoImpl.supprimer(ExerciceDaoImpl.java:190)
	at fr.eseo.atribus.dao.ExerciceDaoImplTest.supprimerExercice(ExerciceDaoImplTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'id_matiere' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
	at fr.eseo.atribus.dao.ExerciceDaoImpl.supprimerAvecRollback(ExerciceDaoImpl.java:208)
	... 27 more
]]>
    </error>
  </testcase> <!-- supprimerExercice -->
  <testcase name="trouverParId" time="0.006" classname="fr.eseo.atribus.dao.ExerciceDaoImplTest"/>
  <testcase name="modifierExercice" time="0.037" classname="fr.eseo.atribus.dao.ExerciceDaoImplTest"/>
</testsuite> <!-- fr.eseo.atribus.dao.ExerciceDaoImplTest -->
